language: node_js
node_js:
  - "latest"

cache:
  yarn: true

script:
  - yarn test
  - yarn build

deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: firebase
  token:
    - $FIREBASE_TOKEN
